apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Apply all dev manifests with a single: kubectl apply -k k8s/dev/
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  environment: development
