name: Deploy

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

run-name: Deploying to S3 and CloudFront

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

permissions:
  id-token: write
  contents: read

jobs:
  build-and-test:
    name: Build and Test
    uses: ./.github/workflows/build-and-test.yaml

  deploy:
    name: Deploy
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: ${{ secrest.AWS_ROLE_SESSION_NAME  }}

      - name: Sync S3 bucket
        run: aws s3 sync dist/ s3://${{ secrets.AWS_S3_BUCKET }} --delete

      - name: Create CloudFront invalidation
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
